### ISSUE TITLE
WEB-060 Money Management

### ISSUE THREAD

**Issue by maubernardi** [avrae/avrae.io#310]
It could be very useful having a command to manage the PC money

I tried using current commands, but I didn't find anything useful...
Could "!money " command be thought for a future?

Thank you!

> Upvote - forgivenknight77#7809

Votes: +1 / -0

**Comment by Infinidoge** [comment]
@maubernardi hello there, unfortunately, this is not the correct place for feature requests pertaining to the bot itself. (This repo is for the site/dashboard.)

The repo you should instead direct these feature requests to is [avrae/avrae](https://github.com/avrae/avrae), which has an issue template for feature requests. 

Additionally, this likely falls under avrae/avrae#1095 
In the meantime, if you join the [Avrae Development Server](https://support.avrae.io), there is the `!coins` alias, which should cover the use-case of this command.
