### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Simonkay11** [avrae/avrae.io#629]
Hello! I have recently discovered this wonderful Bot and have already tried it. But I would like to go further. I think I am able to make a translation of the Application. But I need you to tell me a bit about how Github works. That is, for example, I want to make the command !check Medicine (for example) change it to !check Medicina (which is medicine in Spanish).

I have already modified the Google Docs sheet and it is fully translated into Spanish and it is functional.

**Comment by zhudotexe** [comment]
Hello, thank you for your interest and enthusiasm. Unfortunately at this time an official translation is not a project that we can commit to.
